name: dart_liskov_example
description: A simple command-line application to demonsitrate Liskov Substitution Principle.
version: 1.0.0
homepage: https://better-dev.io/liskov-substitution-principle

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dartz: ^0.9.2
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.9.0
